### ISSUE TITLE
Any android Studio sample project

### ISSUE THREAD

**Issue by mouthdog** [FeitianSmartcardReader/BR500_AND_BR301BLE_SDK_Latest#1]
Do you have any android studio sample project? I try to import the eclipse project in an android studio but can't complete.

**Comment by FeitianSmartcardReader** [comment]
@mouthdog Will make one and upload to git, should be early next week, will keep you update, thanks

**Comment by FeitianSmartcardReader** [comment]
Already had demo code based on android studio.
https://github.com/FeitianSmartcardReader/FEITIAN_MOBILE_READERS/tree/master/Android%20SDK/Sample%20code%20by%20Android%20studio
