### ISSUE TITLE
failed firmware update

### ISSUE THREAD

**Issue by twocanoes** [FeitianSmartcardReader/BR500_AND_BR301BLE_SDK_Latest#2]
I have 2 bR301BLE readers and i tried to update the firmware on both of them. when I ran the update command, it said the uid changed and to unplug and replug in the reader. When I plugged it in again, the charging indicator came on but nothing else and the reader is not usable. The light on the far right (looking at the bottom of the reader, i see the usb port -> power button -> 4 LEDs. The LED in the last position when looking at it that way is the one that turns on when plugged in and turns off when unplugged, but no other LEDs come on and it is not recognized by iOS or Windows any longer. I was able to update the firmware on the br500 successfully but both bR301BLE not longer work. I suspect they are in some flashing mode but am not sure how to resolve. Please help.

**Comment by FeitianSmartcardReader** [comment]
@twocanoes can we have remote session by anydesk allow me to check what's wrong? thanks and looking forward your reply

You can send me the ID to hongbin@ftsafe.com, thanks

**Comment by twocanoes** [comment]
email sent.
